# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.TextField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('pedidos', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.TextField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=5)),
                ('logo', models.FilePathField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ManyToManyField(to='TVirtual.Cliente')),
                ('pedido', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.DetallePedido')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('codigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='foto/')),
                ('descripcion', models.TextField(max_length=2000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('public_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('idC', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idCA',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.Empresa'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='articulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.Stock'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCA',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.Empresa'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='codigo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TVirtual.Stock'),
        ),
    ]
