# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVirtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
